name: mongo-sharding

services:
  configsvr:
    container_name: configsvr
    image: dh-mirror.gitverse.ru/mongo:latest
    command: >
      mongod --configsvr
             --replSet configReplSet
             --port 27019
             --bind_ip_all
    volumes:
      - configsvr_data:/data/db

  shard1:
    container_name: shard1
    image: dh-mirror.gitverse.ru/mongo:latest
    command: >
      mongod --shardsvr
             --replSet shard1ReplSet
             --port 27018
             --bind_ip_all
    volumes:
      - shard1_data:/data/db

  shard2:
    container_name: shard2
    image: dh-mirror.gitverse.ru/mongo:latest
    command: >
      mongod --shardsvr
             --replSet shard2ReplSet
             --port 27018
             --bind_ip_all
    volumes:
      - shard2_data:/data/db

  mongos:
    container_name: mongos
    image: dh-mirror.gitverse.ru/mongo:latest
    depends_on:
      - configsvr
      - shard1
      - shard2
    command: >
      mongos --configdb configReplSet/configsvr:27019
             --port 27017
             --bind_ip_all
    ports:
      - 27017:27017

  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - mongos
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos:27017"
      MONGODB_DATABASE_NAME: "somedb"

volumes:
  configsvr_data:
  shard1_data:
  shard2_data:
